//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HBSFWI_Bibliotek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buecher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buecher()
        {
            this.Auftraege = new HashSet<Auftraege>();
            this.ausleihe_Prozess = new HashSet<ausleihe_Prozess>();
        }
    
        public int ISBN { get; set; }
        public string Buch_Titel { get; set; }
        public string Rechtung { get; set; }
        public string Beschreibung { get; set; }
        public Nullable<int> Anzahl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auftraege> Auftraege { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ausleihe_Prozess> ausleihe_Prozess { get; set; }
    }
}
